<template>
    <article>
        <header-info v-bind="header_info" />

        <!--文本相关样式-->
        <section>
            <p>文本相关样式：</p>
            <table class="table">
                <thead>
                <tr>
                    <th>样式值</th>
                    <th>效果</th>
                    <th>值备注</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><code>pleft</code></td>
                    <td>文本左对齐</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>pright</code></td>
                    <td>文本右对齐</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>pcenter</code></td>
                    <td>文本居中对齐</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>pjustify</code></td>
                    <td>文本两端对齐</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>font-*</code></td>
                    <td>指定字体</td>
                    <td>字体名（需引入对应字体样式文件）</td>
                </tr>
                <tr>
                    <td><code>fsize-*</code></td>
                    <td>字符间距</td>
                    <td>任意合法值，缺省单位 em</td>
                </tr>
                <tr>
                    <td><code>lspace-*</code></td>
                    <td>字符间距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>resize</code></td>
                    <td>重置初始字号及行高</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>ellipsis</code></td>
                    <td>单行文本溢出省略</td>
                    <td>-</td>
                </tr>
                </tbody>
            </table>
            <p></p>
        </section>

        <!--颜色相关样式-->
        <section>
            <p>颜色相关样式：</p>
            <p>可以使用框架预置主题色，包括：none、main、sub、light、dgray、mgray、lgray、dark、red、green、blue、yellow、neutral。色值效果可参考 <b>"全局样式 - 色彩"</b>，此外其它任意标准 web 色彩模式都可以直接使用。</p>
            <p>主题色支持扩展及修改，通常可在全局文件 <b>main.js</b> 引入 <code>BTXUI/core/styles/theme.js</code> 模块，执行 <code>append(colors)</code> 方法扩展。</p>
            <p>【exp】扩展深红色：<code>Theme.append({ deep_red: "#ae0014" })</code></p>
            <table class="table">
                <thead>
                <tr>
                    <th>样式值</th>
                    <th>效果</th>
                    <th>值备注</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><code>bg-color-*</code></td>
                    <td>背景色</td>
                    <td>任意合法值或主题色</td>
                </tr>
                <tr>
                    <td><code>color-*</code></td>
                    <td>文字色</td>
                    <td>任意合法值或主题色</td>
                </tr>
                <tr>
                    <td><code>line-*</code></td>
                    <td>描边色</td>
                    <td>任意合法值或主题色</td>
                </tr>
                <tr>
                    <td><code>alpha-*</code></td>
                    <td>不透明度</td>
                    <td>值域范围：0 - 1</td>
                </tr>
                </tbody>
            </table>
            <p></p>
        </section>

        <!--布局相关样式-->
        <section>
            <p>布局相关样式：</p>
            <table class="table">
                <thead>
                <tr>
                    <th>样式值</th>
                    <th>效果</th>
                    <th>值备注</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><code>show</code></td>
                    <td>显示元素</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>hide</code></td>
                    <td>隐藏元素</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>flex</code></td>
                    <td>弹性布局容器</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>flex-*</code></td>
                    <td>弹性布局容器，九宫格式布局</td>
                    <td>值域范围：1 - 9</td>
                </tr>
                <tr>
                    <td><code>flex-between</code></td>
                    <td>弹性布局容器，均分排列，两端对齐</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>flex-around</code></td>
                    <td>弹性布局容器，均分排列</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>grid</code></td>
                    <td>弹性布局容器，可换行</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>flex-column</code></td>
                    <td>弹性布局容器，纵向生长</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>grow-*</code></td>
                    <td>元素自生长比率</td>
                    <td>任意合法值</td>
                </tr>
                <tr>
                    <td><code>order-*</code></td>
                    <td>弹性布局项目排序</td>
                    <td>任意合法值</td>
                </tr>
                <tr>
                    <td><code>column-*</code></td>
                    <td>多列布局容器</td>
                    <td>任意合法值</td>
                </tr>
                <tr>
                    <td><code>item</code></td>
                    <td>多列布局元素</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>pad-*</code></td>
                    <td>内边距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>pad-l-*</code></td>
                    <td>左侧内边距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>pad-r-*</code></td>
                    <td>右侧内边距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>pad-t-*</code></td>
                    <td>上侧内边距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>pad-b-*</code></td>
                    <td>下侧内边距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>pad-v-*</code></td>
                    <td>垂直方向内边距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>pad-h-*</code></td>
                    <td>水平方向内边距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>mrg-*</code></td>
                    <td>外边距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>mrg-l-*</code></td>
                    <td>左侧外边距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>mrg-r-*</code></td>
                    <td>右侧外边距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>mrg-t-*</code></td>
                    <td>上侧外边距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>mrg-b-*</code></td>
                    <td>下侧外边距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>mrg-v-*</code></td>
                    <td>垂直方向外边距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>mrg-h-*</code></td>
                    <td>水平方向外边距</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>max-h</code></td>
                    <td>高度布满父容器</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>max-w</code></td>
                    <td>宽度布满父容器</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>max</code></td>
                    <td>宽高布满父容器</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>max-screen</code></td>
                    <td>全屏且溢出隐藏</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>h-*</code></td>
                    <td>设置高度</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>lh-*</code></td>
                    <td>设置行高</td>
                    <td>任意合法值</td>
                </tr>
                <tr>
                    <td><code>w-*</code></td>
                    <td>设置宽度</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>lw-*</code></td>
                    <td>设置最小宽度</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>rw-*</code></td>
                    <td>设置最大宽度</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>bh-*</code></td>
                    <td>设置最小高度</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>th-*</code></td>
                    <td>设置最大高度</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>fixed</code></td>
                    <td>固定式定位</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>rel</code></td>
                    <td>相对定位</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>abs</code></td>
                    <td>绝对定位</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>z*</code></td>
                    <td>z 轴层级</td>
                    <td>值域范围：-1 - 10</td>
                </tr>
                <tr>
                    <td><code>no-scroll | over-hide</code></td>
                    <td>内容溢出隐藏</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>over-show</code></td>
                    <td>内容溢出显示</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>over-scroll</code></td>
                    <td>内容溢出滚动</td>
                    <td>-</td>
                </tr>
                </tbody>
            </table>
            <p></p>
        </section>

        <!--位移及变形微调相关样式-->
        <section>
            <p>位移及变形微调相关样式：</p>
            <p>和全局样式稍有不同，基于百分比值的位移直接使用 "%" 单位而非 "p"。</p>
            <table class="table">
                <thead>
                <tr>
                    <th>样式值</th>
                    <th>效果</th>
                    <th>值备注</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><code>l-*</code></td>
                    <td>基于容器左侧水平位移</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>r-*</code></td>
                    <td>基于容器右侧水平位移</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>t-*</code></td>
                    <td>基于容器上侧垂直位移</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>b-*</code></td>
                    <td>基于容器下侧垂直位移</td>
                    <td>任意合法值，缺省单位 rem</td>
                </tr>
                <tr>
                    <td><code>translateX-*</code></td>
                    <td>基于自身水平位移</td>
                    <td>任意合法值，缺省单位 %</td>
                </tr>
                <tr>
                    <td><code>translateY-*</code></td>
                    <td>基于自身垂直位移</td>
                    <td>任意合法值，缺省单位 %</td>
                </tr>
                <tr>
                    <td><code>scale-*</code></td>
                    <td>放缩</td>
                    <td>任意合法值</td>
                </tr>
                <tr>
                    <td><code>rotate-*</code></td>
                    <td>旋转</td>
                    <td>任意合法值</td>
                </tr>
                </tbody>
            </table>
            <p>此外可以通过 <code>transform-*</code> 设置任意二维变形效果；以及 <code>origin-*</code> 设置变形中心点。</p>
            <table class="table">
                <thead>
                <tr>
                    <th>样式值</th>
                    <th>效果</th>
                    <th>示例</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><code>transform-*</code></td>
                    <td>自由变形元素</td>
                    <td><code>transform-scale(1.1)rotate(45deg)</code></td>
                </tr>
                <tr>
                    <td><code>origin-*</code></td>
                    <td>设置变形中心点</td>
                    <td><code>origin-20px|50%</code></td>
                </tr>
                </tbody>
            </table>
            <p></p>
        </section>

        <!--背景相关样式-->
        <section>
            <p>背景相关样式：</p>
            <p>b-view 组件使用 bg-img 属性引入背景图片。</p>
            <p>相比全局样式，styles 属性支持任意合法值的背景图尺寸及定位设置，且支持 <code>bg-gradient-*</code> 线性渐变背景设置。</p>
            <table class="table">
                <thead>
                <tr>
                    <th>样式值</th>
                    <th>效果</th>
                    <th>值备注</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><code>bg-*</code></td>
                    <td>综合背景样式</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>bg-repeat</code></td>
                    <td>背景图水平及垂直平铺</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>bg-repeat-x</code></td>
                    <td>背景图水平平铺</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>bg-repeat-y</code></td>
                    <td>背景图垂直平铺</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>bg-size-cover</code></td>
                    <td>背景图尺寸覆盖容器</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>bg-size-contain</code></td>
                    <td>背景图尺寸适应容器</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>bg-size-max</code></td>
                    <td>背景图尺寸撑满容器</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>bg-size-max-h</code></td>
                    <td>背景图高度尺寸撑满容器</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>bg-size-max-w</code></td>
                    <td>背景图宽度尺寸撑满容器</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>bg-size-*</code></td>
                    <td>背景图尺寸设置</td>
                    <td>任意合法值</td>
                </tr>
                <tr>
                    <td><code>bg-pos-*</code></td>
                    <td>背景图九宫格定位</td>
                    <td>值域范围：1 - 9</td>
                </tr>
                <tr>
                    <td><code>bg-pos-*</code></td>
                    <td>背景图定位</td>
                    <td>任意合法值</td>
                </tr>
                <tr>
                    <td><code>bg-gradient-*</code></td>
                    <td>线性渐变背景</td>
                    <td>任意合法值</td>
                </tr>
                </tbody>
            </table>
            <p></p>
        </section>

        <!--圆角相关样式-->
        <section>
            <p>圆角相关样式：</p>
            <table class="table">
                <thead>
                <tr>
                    <th>样式值</th>
                    <th>效果</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <code>round</code>
                    </td>
                    <td>50% 圆角，可用于制作正圆形或椭圆形</td>
                </tr>
                <tr>
                    <td>
                        <code>round-lg</code>
                    </td>
                    <td>24px 大圆角</td>
                </tr>
                <tr>
                    <td>
                        <code>round-md</code>
                    </td>
                    <td>10px 中等圆角</td>
                </tr>
                <tr>
                    <td>
                        <code>round-sm</code>
                    </td>
                    <td>4px 小型圆角</td>
                </tr>
                <tr>
                    <td>
                        <code>round-t</code>
                    </td>
                    <td>上侧圆角</td>
                </tr>
                <tr>
                    <td>
                        <code>round-b</code>
                    </td>
                    <td>下侧圆角</td>
                </tr>
                <tr>
                    <td>
                        <code>round-l</code>
                    </td>
                    <td>左侧圆角</td>
                </tr>
                <tr>
                    <td>
                        <code>round-r</code>
                    </td>
                    <td>右侧圆角</td>
                </tr>
                </tbody>
            </table>
            <p></p>
        </section>

        <!--描边及阴影相关样式-->
        <section>
            <p>描边及阴影相关样式：</p>
            <table class="table">
                <thead>
                <tr>
                    <th>样式值</th>
                    <th>效果</th>
                    <th>值备注</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <code>line</code>
                    </td>
                    <td>设置四周实线描边</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>line-l</code>
                    </td>
                    <td>设置左侧实线描边</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>line-r</code>
                    </td>
                    <td>设置右侧实线描边</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>line-t</code>
                    </td>
                    <td>设置上侧实线描边</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>line-b</code>
                    </td>
                    <td>设置下侧实线描边</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>dashed</code>
                    </td>
                    <td>设置四周虚线描边</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>dashed-l</code>
                    </td>
                    <td>设置左侧虚线描边</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>dashed-r</code>
                    </td>
                    <td>设置右侧虚线描边</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>dashed-t</code>
                    </td>
                    <td>设置上侧虚线描边</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>dashed-b</code>
                    </td>
                    <td>设置下侧虚线描边</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>line-outside</code>
                    </td>
                    <td>设置外侧描边范围</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>thick-*</code>
                    </td>
                    <td>设置描边粗细</td>
                    <td>任意合法值，缺省单位 px</td>
                </tr>
                <tr>
                    <td>
                        <code>text-line</code>
                    </td>
                    <td>文字描边</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>shadow</code>
                    </td>
                    <td>普通尺寸阴影</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>shadow-sm</code>
                    </td>
                    <td>小尺寸阴影</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>shadow-lg</code>
                    </td>
                    <td>大尺寸阴影</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>shadow-relief</code>
                    </td>
                    <td>浮雕阴影效果</td>
                    <td>-</td>
                </tr>
                </tbody>
            </table>
            <p></p>
        </section>

        <!--滤镜相关样式-->
        <section>
            <p>滤镜相关样式：</p>
            <table class="table">
                <thead>
                <tr>
                    <th>样式类</th>
                    <th>效果</th>
                    <th>值备注</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <code>.blur-no</code>
                    </td>
                    <td>无模糊效果</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>.blur-sm</code>
                    </td>
                    <td>轻度模糊效果</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>.blur-md</code>
                    </td>
                    <td>中度模糊效果</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>.blur-lg</code>
                    </td>
                    <td>重度模糊效果</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>.dark-no</code>
                    </td>
                    <td>原始明度效果</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>.dark-sm</code>
                    </td>
                    <td>轻度低明度效果</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>.dark-md</code>
                    </td>
                    <td>中度低明度效果</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>.dark-lg</code>
                    </td>
                    <td>重度低明度效果</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>.gray-no</code>
                    </td>
                    <td>原始纯度效果</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>.gray-sm</code>
                    </td>
                    <td>轻度低纯度效果</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>.gray-md</code>
                    </td>
                    <td>中度低纯度效果</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>.gray-lg</code>
                    </td>
                    <td>重度低纯度效果</td>
                    <td>-</td>
                </tr>
                </tbody>
            </table>
            <p></p>
        </section>

        <!--过渡动画相关样式-->
        <section>
            <p>过渡动画相关样式：</p>
            <table class="table">
                <thead>
                <tr>
                    <th>样式值</th>
                    <th>效果</th>
                    <th>值备注</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <code>trans</code>
                    </td>
                    <td>中速过度动画（.7s）</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>trans-fast</code>
                    </td>
                    <td>快速过度动画（.4s）</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>trans-slow</code>
                    </td>
                    <td>慢速过度动画（1.4s）</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>trans-no</code>
                    </td>
                    <td>无过度动画</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>
                        <code>trans-delay-*</code>
                    </td>
                    <td>动画延迟执行时间</td>
                    <td>任意合法值，缺省单位 s</td>
                </tr>
                </tbody>
            </table>
            <p></p>
        </section>

        <!--特殊样式控制-->
        <section>
            <p>特殊样式控制：</p>
            <table class="table">
                <thead>
                <tr>
                    <th>样式值</th>
                    <th>效果</th>
                    <th>值备注</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><code>bg-none</code></td>
                    <td>背景点透效果</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>bg-use</code></td>
                    <td>背景常规效果（非点透）</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td><code>touch-none</code></td>
                    <td>默认触控禁止</td>
                    <td>-</td>
                </tr>
                </tbody>
            </table>
        </section>

    </article>
</template>

<script>
    import HeaderInfo from "@/components/header-info"
    import BStyle from "@/components/BTXUI/core/styles/b-style"

    export default {
        name: "b_style_demo",
        components: {
            HeaderInfo
        },
        data() {
            return {

                //初始化入参
                header_info: {
                    name: BStyle.name,
                    ...BStyle.introduce,
                }

            }
        }
    }
</script>